# Generated by map_wizard.py
# 3 rows x 5 cols, row-major order for KMK PINS list.
# Replace the PINS = [...] block in your KMK code.py with this.

import board

PINS = [
    board.GP22, board.GP19, board.GP2, board.GP5, board.GP8,  # row 0
    board.GP21, board.GP18, board.GP3, board.GP6, board.GP9,  # row 1
    board.GP20, board.GP17, board.GP4, board.GP7, board.GP10,  # row 2
]
